(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const s of document.querySelectorAll('link[rel="modulepreload"]'))n(s);new MutationObserver(s=>{for(const o of s)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function t(s){const o={};return s.integrity&&(o.integrity=s.integrity),s.referrerPolicy&&(o.referrerPolicy=s.referrerPolicy),s.crossOrigin==="use-credentials"?o.credentials="include":s.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(s){if(s.ep)return;s.ep=!0;const o=t(s);fetch(s.href,o)}})();const a={btnToggleTheme:document.querySelector(".btn-toggle-theme"),formAddTask:document.querySelector(".form-add-task"),newTaskName:document.querySelector("#task-name"),newTaskDescr:document.querySelector("#task-description"),btnAddTask:document.querySelector(".btn-add-task"),taskList:document.querySelector("#task-list")};function k(e,r){let t=l(),n=g();t===null&&(t=[],n=0),n=n+1,t.push({id:n,name:e,description:r}),localStorage.setItem("tasks",JSON.stringify(t)),localStorage.setItem("lastId",JSON.stringify(n))}function l(){const e=localStorage.getItem("tasks");return JSON.parse(e)}function g(){const e=localStorage.getItem("lastId");return JSON.parse(e)}function u(e){localStorage.setItem("theme",e)}function m(){let e=localStorage.getItem("theme");return e===null&&(e="light",u(e)),e}function f(e){e==="dark"?document.body.setAttribute("data-theme","dark"):document.body.setAttribute("data-theme","light")}function c(e){return e.map(t=>`
        <li class="task-item" id="${t.id}">
          <div class="task-content">
            <p class="id">${t.id}</p>
            <p class="name">${t.name}</p>
            <p class="description">${t.description}</p>
          </div>
          <button type="button" class="btn-delete-task">Delete</button>
        </li>`).join("")}f(m());let d=l();if(d!==null){let e=c(d);a.taskList.insertAdjacentHTML("beforeend",e)}a.formAddTask.addEventListener("submit",p);function p(e){e.preventDefault();const r=a.newTaskName.value.trim();a.newTaskName.value=r;const t=a.newTaskDescr.value.trim();if(a.newTaskDescr.value=t,console.log("taskName",r),console.log("taskDescr",t),r===""||t===""){console.log("ERROR");return}k(r,t),a.taskList.innerHTML="";let n=l(),s=c(n);a.taskList.insertAdjacentHTML("beforeend",s),a.formAddTask.reset()}a.taskList.addEventListener("click",T);function T(e){if(e.target.tagName!=="BUTTON")return;const r=e.target.closest("li"),t=Number(r.id);let n=l();console.log("tasks",n);let s=n.filter(i=>i.id!==t);console.log("newTasks",s),localStorage.setItem("tasks",JSON.stringify(s)),a.taskList.innerHTML="";let o=c(s);a.taskList.insertAdjacentHTML("beforeend",o)}a.btnToggleTheme.addEventListener("click",L);function L(e){let r=m(),t;r==="dark"?t="light":t="dark",f(t),u(t)}
//# sourceMappingURL=index.js.map
